---
- name: Install OS package dependencies
  become: yes
  become_user: root
  with_items: '{{ anaconda_dep_pkgs | default([]) }}'
  loop_control:
    loop_var: anaconda_os_pkg
  package:
    state: present
    name: '{{ anaconda_os_pkg }}'

- name: Check for installation of Anaconda
  become: yes
  stat:
    path: '{{ anaconda_install_dir }}/bin/conda'
  changed_when: false
  register: anaconda_conda_binary

- when: not anaconda_conda_binary.stat.exists
  block:
    - name: Download Anaconda installer.
      become: yes
      become_user: root
      get_url:
        url: '{{anaconda_installer_url}}'
        dest: /tmp/{{anaconda_installer_sh}}
        timeout: '{{anaconda_timeout_seconds}}'
        checksum: '{{anaconda_checksum}}'
        mode: 0755

    - name: Run Anaconda installer.
      become: yes
      become_user: root
      command: bash /tmp/{{anaconda_installer_sh}} -b -p {{anaconda_install_dir}}
      args:
        creates: '{{anaconda_install_dir}}'

  always:
    - name: Delete Anaconda installer.
      become: yes
      become_user: root
      file:
        path: /tmp/{{anaconda_installer_sh}}
        state: absent

# Is conda-curl even installed by default or is this just another Blackrock thing?
- name: Remove conda-curl since it conflicts with the system curl
  become: yes
  become_user: root
  command: '{{anaconda_install_dir}}/bin/conda remove -y curl'
  
- name: Add Anaconda to universal bash profile.
  become: yes
  become_user: root
  when: anaconda_make_sys_default
  command: '{{anaconda_install_dir}}/bin/conda init --system'

- name: Add conda base environment file.
  become: yes
  become_user: root
  copy:
    content: '{{ anaconda_base_env | to_nice_yaml }}'
    dest: /tmp/anaconda-base.yml
  when: anaconda_base_env is defined

- name: Install additional packages to universal install / add default packages to shared package cache.
  become: yes
  become_user: root
  command: '{{anaconda_install_dir}}/bin/conda env update -f=/tmp/anaconda-base.yml'
  when: anaconda_base_env is defined

- name: Remove conda base environment file.
  become: yes
  become_user: root
  file:
    path: /tmp/anaconda-base.yml
    state: absent
  when: anaconda_base_env is defined

- name: Update conda packages to latest versions.
  become: yes
  become_user: root
  when: anaconda_pkg_update
  command: '{{anaconda_install_dir}}/bin/conda update -y --all'

